# Installed to /etc/sddm.conf.d/ by install.sh
[General]
InputMethod=qtvirtualkeyboard
GreeterEnvironment=QML2_IMPORT_PATH=/usr/share/sddm/themes/custom/components/,QT_IM_MODULE=qtvirtualkeyboard

[Theme]
Current=custom

[X11]
DisplayCommand=/etc/sddm/Xsetup
